// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/calculator.proto

package gogen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DoubleRequest struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleRequest) Reset()         { *m = DoubleRequest{} }
func (m *DoubleRequest) String() string { return proto.CompactTextString(m) }
func (*DoubleRequest) ProtoMessage()    {}
func (*DoubleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3345fe153a3a1fee, []int{0}
}

func (m *DoubleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleRequest.Unmarshal(m, b)
}
func (m *DoubleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleRequest.Marshal(b, m, deterministic)
}
func (m *DoubleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleRequest.Merge(m, src)
}
func (m *DoubleRequest) XXX_Size() int {
	return xxx_messageInfo_DoubleRequest.Size(m)
}
func (m *DoubleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleRequest proto.InternalMessageInfo

func (m *DoubleRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *DoubleRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type SingleResponse struct {
	Res                  int32    `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleResponse) Reset()         { *m = SingleResponse{} }
func (m *SingleResponse) String() string { return proto.CompactTextString(m) }
func (*SingleResponse) ProtoMessage()    {}
func (*SingleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3345fe153a3a1fee, []int{1}
}

func (m *SingleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleResponse.Unmarshal(m, b)
}
func (m *SingleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleResponse.Marshal(b, m, deterministic)
}
func (m *SingleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleResponse.Merge(m, src)
}
func (m *SingleResponse) XXX_Size() int {
	return xxx_messageInfo_SingleResponse.Size(m)
}
func (m *SingleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SingleResponse proto.InternalMessageInfo

func (m *SingleResponse) GetRes() int32 {
	if m != nil {
		return m.Res
	}
	return 0
}

func init() {
	proto.RegisterType((*DoubleRequest)(nil), "calculator.DoubleRequest")
	proto.RegisterType((*SingleResponse)(nil), "calculator.SingleResponse")
}

func init() { proto.RegisterFile("api/calculator.proto", fileDescriptor_3345fe153a3a1fee) }

var fileDescriptor_3345fe153a3a1fee = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0xc8, 0xd4,
	0x4f, 0x4e, 0xcc, 0x49, 0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x42, 0x88, 0x28, 0x69, 0x73, 0xf1, 0xba, 0xe4, 0x97, 0x26, 0xe5, 0xa4, 0x06, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x70, 0x31, 0x26, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x31, 0x26, 0x82, 0x78, 0x49, 0x12, 0x4c, 0x10, 0x5e, 0x92, 0x92, 0x12, 0x17, 0x5f, 0x70,
	0x66, 0x5e, 0x3a, 0x48, 0x71, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x51,
	0x6a, 0x31, 0x54, 0x3d, 0x88, 0x69, 0x74, 0x99, 0x89, 0x4b, 0xd0, 0x19, 0x6e, 0x7e, 0x70, 0x6a,
	0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x1d, 0x17, 0xb3, 0x63, 0x4a, 0x8a, 0x90, 0xa4, 0x1e, 0x92,
	0x63, 0x50, 0xec, 0x95, 0x92, 0x42, 0x96, 0x42, 0xb5, 0x45, 0x89, 0x01, 0xa4, 0x3f, 0xb8, 0x34,
	0x89, 0x22, 0xfd, 0xbe, 0xa5, 0x39, 0x14, 0xe9, 0x77, 0xc9, 0x2c, 0xa3, 0xcc, 0xfe, 0x7c, 0xf2,
	0xfd, 0xef, 0xc4, 0x1d, 0xc5, 0x59, 0x90, 0x9d, 0xae, 0x9f, 0x9e, 0x9f, 0x9e, 0x9a, 0x97, 0xc4,
	0x06, 0x8e, 0x46, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x37, 0x39, 0x65, 0xde, 0x01,
	0x00, 0x00,
}
